// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: hq/v1/common.proto

package hqv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Market int32

const (
	Market_A_SHARE Market = 0
	Market_HK      Market = 1
	Market_US      Market = 2
	Market_CRYPTO  Market = 3
)

// Enum value maps for Market.
var (
	Market_name = map[int32]string{
		0: "A_SHARE",
		1: "HK",
		2: "US",
		3: "CRYPTO",
	}
	Market_value = map[string]int32{
		"A_SHARE": 0,
		"HK":      1,
		"US":      2,
		"CRYPTO":  3,
	}
)

func (x Market) Enum() *Market {
	p := new(Market)
	*p = x
	return p
}

func (x Market) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Market) Descriptor() protoreflect.EnumDescriptor {
	return file_hq_v1_common_proto_enumTypes[0].Descriptor()
}

func (Market) Type() protoreflect.EnumType {
	return &file_hq_v1_common_proto_enumTypes[0]
}

func (x Market) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Market.Descriptor instead.
func (Market) EnumDescriptor() ([]byte, []int) {
	return file_hq_v1_common_proto_rawDescGZIP(), []int{0}
}

var File_hq_v1_common_proto protoreflect.FileDescriptor

const file_hq_v1_common_proto_rawDesc = "" +
	"\n" +
	"\x12hq/v1/common.proto\x12\x05hq.v1*1\n" +
	"\x06Market\x12\v\n" +
	"\aA_SHARE\x10\x00\x12\x06\n" +
	"\x02HK\x10\x01\x12\x06\n" +
	"\x02US\x10\x02\x12\n" +
	"\n" +
	"\x06CRYPTO\x10\x03Ba\n" +
	"\x18com.hqpush.contract.hqv1B\vCommonProtoP\x01Z6github.com/hqpush/gate/packages/contract/go/hq/v1;hqv1b\x06proto3"

var (
	file_hq_v1_common_proto_rawDescOnce sync.Once
	file_hq_v1_common_proto_rawDescData []byte
)

func file_hq_v1_common_proto_rawDescGZIP() []byte {
	file_hq_v1_common_proto_rawDescOnce.Do(func() {
		file_hq_v1_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_hq_v1_common_proto_rawDesc), len(file_hq_v1_common_proto_rawDesc)))
	})
	return file_hq_v1_common_proto_rawDescData
}

var file_hq_v1_common_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_hq_v1_common_proto_goTypes = []any{
	(Market)(0), // 0: hq.v1.Market
}
var file_hq_v1_common_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_hq_v1_common_proto_init() }
func file_hq_v1_common_proto_init() {
	if File_hq_v1_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_hq_v1_common_proto_rawDesc), len(file_hq_v1_common_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_hq_v1_common_proto_goTypes,
		DependencyIndexes: file_hq_v1_common_proto_depIdxs,
		EnumInfos:         file_hq_v1_common_proto_enumTypes,
	}.Build()
	File_hq_v1_common_proto = out.File
	file_hq_v1_common_proto_goTypes = nil
	file_hq_v1_common_proto_depIdxs = nil
}
