// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: hq/v1/market.proto

package hqv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 标准化行情 tick —— 全链路统一携带 market
type Tick struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Market        Market                 `protobuf:"varint,1,opt,name=market,proto3,enum=hq.v1.Market" json:"market,omitempty"`
	Symbol        string                 `protobuf:"bytes,2,opt,name=symbol,proto3" json:"symbol,omitempty"` // 600000 / AAPL / 00700 / BTC-USDT
	Exchange      string                 `protobuf:"bytes,3,opt,name=exchange,proto3" json:"exchange,omitempty"`
	TimestampMs   int64                  `protobuf:"varint,4,opt,name=timestamp_ms,json=timestampMs,proto3" json:"timestamp_ms,omitempty"`
	LastPrice     float64                `protobuf:"fixed64,5,opt,name=last_price,json=lastPrice,proto3" json:"last_price,omitempty"`
	Open          float64                `protobuf:"fixed64,6,opt,name=open,proto3" json:"open,omitempty"`
	High          float64                `protobuf:"fixed64,7,opt,name=high,proto3" json:"high,omitempty"`
	Low           float64                `protobuf:"fixed64,8,opt,name=low,proto3" json:"low,omitempty"`
	PreClose      float64                `protobuf:"fixed64,9,opt,name=pre_close,json=preClose,proto3" json:"pre_close,omitempty"` // 昨收，用于涨跌幅
	Volume        float64                `protobuf:"fixed64,10,opt,name=volume,proto3" json:"volume,omitempty"`                    // 累计成交量
	Amount        float64                `protobuf:"fixed64,11,opt,name=amount,proto3" json:"amount,omitempty"`                    // 累计成交额
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Tick) Reset() {
	*x = Tick{}
	mi := &file_hq_v1_market_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tick) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tick) ProtoMessage() {}

func (x *Tick) ProtoReflect() protoreflect.Message {
	mi := &file_hq_v1_market_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tick.ProtoReflect.Descriptor instead.
func (*Tick) Descriptor() ([]byte, []int) {
	return file_hq_v1_market_proto_rawDescGZIP(), []int{0}
}

func (x *Tick) GetMarket() Market {
	if x != nil {
		return x.Market
	}
	return Market_A_SHARE
}

func (x *Tick) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *Tick) GetExchange() string {
	if x != nil {
		return x.Exchange
	}
	return ""
}

func (x *Tick) GetTimestampMs() int64 {
	if x != nil {
		return x.TimestampMs
	}
	return 0
}

func (x *Tick) GetLastPrice() float64 {
	if x != nil {
		return x.LastPrice
	}
	return 0
}

func (x *Tick) GetOpen() float64 {
	if x != nil {
		return x.Open
	}
	return 0
}

func (x *Tick) GetHigh() float64 {
	if x != nil {
		return x.High
	}
	return 0
}

func (x *Tick) GetLow() float64 {
	if x != nil {
		return x.Low
	}
	return 0
}

func (x *Tick) GetPreClose() float64 {
	if x != nil {
		return x.PreClose
	}
	return 0
}

func (x *Tick) GetVolume() float64 {
	if x != nil {
		return x.Volume
	}
	return 0
}

func (x *Tick) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

// 周期闭合K线
type Kline struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Market        Market                 `protobuf:"varint,1,opt,name=market,proto3,enum=hq.v1.Market" json:"market,omitempty"`
	Symbol        string                 `protobuf:"bytes,2,opt,name=symbol,proto3" json:"symbol,omitempty"`
	PeriodMin     int32                  `protobuf:"varint,3,opt,name=period_min,json=periodMin,proto3" json:"period_min,omitempty"` // 1/5/15/30/60/1440(日)
	BeginTsMs     int64                  `protobuf:"varint,4,opt,name=begin_ts_ms,json=beginTsMs,proto3" json:"begin_ts_ms,omitempty"`
	Open          float64                `protobuf:"fixed64,5,opt,name=open,proto3" json:"open,omitempty"`
	High          float64                `protobuf:"fixed64,6,opt,name=high,proto3" json:"high,omitempty"`
	Low           float64                `protobuf:"fixed64,7,opt,name=low,proto3" json:"low,omitempty"`
	Close         float64                `protobuf:"fixed64,8,opt,name=close,proto3" json:"close,omitempty"`
	Volume        float64                `protobuf:"fixed64,9,opt,name=volume,proto3" json:"volume,omitempty"`
	Amount        float64                `protobuf:"fixed64,10,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Kline) Reset() {
	*x = Kline{}
	mi := &file_hq_v1_market_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Kline) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Kline) ProtoMessage() {}

func (x *Kline) ProtoReflect() protoreflect.Message {
	mi := &file_hq_v1_market_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Kline.ProtoReflect.Descriptor instead.
func (*Kline) Descriptor() ([]byte, []int) {
	return file_hq_v1_market_proto_rawDescGZIP(), []int{1}
}

func (x *Kline) GetMarket() Market {
	if x != nil {
		return x.Market
	}
	return Market_A_SHARE
}

func (x *Kline) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *Kline) GetPeriodMin() int32 {
	if x != nil {
		return x.PeriodMin
	}
	return 0
}

func (x *Kline) GetBeginTsMs() int64 {
	if x != nil {
		return x.BeginTsMs
	}
	return 0
}

func (x *Kline) GetOpen() float64 {
	if x != nil {
		return x.Open
	}
	return 0
}

func (x *Kline) GetHigh() float64 {
	if x != nil {
		return x.High
	}
	return 0
}

func (x *Kline) GetLow() float64 {
	if x != nil {
		return x.Low
	}
	return 0
}

func (x *Kline) GetClose() float64 {
	if x != nil {
		return x.Close
	}
	return 0
}

func (x *Kline) GetVolume() float64 {
	if x != nil {
		return x.Volume
	}
	return 0
}

func (x *Kline) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

var File_hq_v1_market_proto protoreflect.FileDescriptor

const file_hq_v1_market_proto_rawDesc = "" +
	"\n" +
	"\x12hq/v1/market.proto\x12\x05hq.v1\x1a\x12hq/v1/common.proto\"\xaa\x02\n" +
	"\x04Tick\x12%\n" +
	"\x06market\x18\x01 \x01(\x0e2\r.hq.v1.MarketR\x06market\x12\x16\n" +
	"\x06symbol\x18\x02 \x01(\tR\x06symbol\x12\x1a\n" +
	"\bexchange\x18\x03 \x01(\tR\bexchange\x12!\n" +
	"\ftimestamp_ms\x18\x04 \x01(\x03R\vtimestampMs\x12\x1d\n" +
	"\n" +
	"last_price\x18\x05 \x01(\x01R\tlastPrice\x12\x12\n" +
	"\x04open\x18\x06 \x01(\x01R\x04open\x12\x12\n" +
	"\x04high\x18\a \x01(\x01R\x04high\x12\x10\n" +
	"\x03low\x18\b \x01(\x01R\x03low\x12\x1b\n" +
	"\tpre_close\x18\t \x01(\x01R\bpreClose\x12\x16\n" +
	"\x06volume\x18\n" +
	" \x01(\x01R\x06volume\x12\x16\n" +
	"\x06amount\x18\v \x01(\x01R\x06amount\"\x85\x02\n" +
	"\x05Kline\x12%\n" +
	"\x06market\x18\x01 \x01(\x0e2\r.hq.v1.MarketR\x06market\x12\x16\n" +
	"\x06symbol\x18\x02 \x01(\tR\x06symbol\x12\x1d\n" +
	"\n" +
	"period_min\x18\x03 \x01(\x05R\tperiodMin\x12\x1e\n" +
	"\vbegin_ts_ms\x18\x04 \x01(\x03R\tbeginTsMs\x12\x12\n" +
	"\x04open\x18\x05 \x01(\x01R\x04open\x12\x12\n" +
	"\x04high\x18\x06 \x01(\x01R\x04high\x12\x10\n" +
	"\x03low\x18\a \x01(\x01R\x03low\x12\x14\n" +
	"\x05close\x18\b \x01(\x01R\x05close\x12\x16\n" +
	"\x06volume\x18\t \x01(\x01R\x06volume\x12\x16\n" +
	"\x06amount\x18\n" +
	" \x01(\x01R\x06amountBa\n" +
	"\x18com.hqpush.contract.hqv1B\vMarketProtoP\x01Z6github.com/hqpush/gate/packages/contract/go/hq/v1;hqv1b\x06proto3"

var (
	file_hq_v1_market_proto_rawDescOnce sync.Once
	file_hq_v1_market_proto_rawDescData []byte
)

func file_hq_v1_market_proto_rawDescGZIP() []byte {
	file_hq_v1_market_proto_rawDescOnce.Do(func() {
		file_hq_v1_market_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_hq_v1_market_proto_rawDesc), len(file_hq_v1_market_proto_rawDesc)))
	})
	return file_hq_v1_market_proto_rawDescData
}

var file_hq_v1_market_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_hq_v1_market_proto_goTypes = []any{
	(*Tick)(nil),  // 0: hq.v1.Tick
	(*Kline)(nil), // 1: hq.v1.Kline
	(Market)(0),   // 2: hq.v1.Market
}
var file_hq_v1_market_proto_depIdxs = []int32{
	2, // 0: hq.v1.Tick.market:type_name -> hq.v1.Market
	2, // 1: hq.v1.Kline.market:type_name -> hq.v1.Market
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_hq_v1_market_proto_init() }
func file_hq_v1_market_proto_init() {
	if File_hq_v1_market_proto != nil {
		return
	}
	file_hq_v1_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_hq_v1_market_proto_rawDesc), len(file_hq_v1_market_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_hq_v1_market_proto_goTypes,
		DependencyIndexes: file_hq_v1_market_proto_depIdxs,
		MessageInfos:      file_hq_v1_market_proto_msgTypes,
	}.Build()
	File_hq_v1_market_proto = out.File
	file_hq_v1_market_proto_goTypes = nil
	file_hq_v1_market_proto_depIdxs = nil
}
