// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: hq/v1/push.proto

package hqv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RuleType int32

const (
	RuleType_PRICE_ABOVE RuleType = 0
	RuleType_PRICE_BELOW RuleType = 1
	RuleType_PRICE_RANGE RuleType = 2
	RuleType_PCT_CHANGE  RuleType = 3
	RuleType_INDICATOR   RuleType = 4
)

// Enum value maps for RuleType.
var (
	RuleType_name = map[int32]string{
		0: "PRICE_ABOVE",
		1: "PRICE_BELOW",
		2: "PRICE_RANGE",
		3: "PCT_CHANGE",
		4: "INDICATOR",
	}
	RuleType_value = map[string]int32{
		"PRICE_ABOVE": 0,
		"PRICE_BELOW": 1,
		"PRICE_RANGE": 2,
		"PCT_CHANGE":  3,
		"INDICATOR":   4,
	}
)

func (x RuleType) Enum() *RuleType {
	p := new(RuleType)
	*p = x
	return p
}

func (x RuleType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RuleType) Descriptor() protoreflect.EnumDescriptor {
	return file_hq_v1_push_proto_enumTypes[0].Descriptor()
}

func (RuleType) Type() protoreflect.EnumType {
	return &file_hq_v1_push_proto_enumTypes[0]
}

func (x RuleType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RuleType.Descriptor instead.
func (RuleType) EnumDescriptor() ([]byte, []int) {
	return file_hq_v1_push_proto_rawDescGZIP(), []int{0}
}

// 规则广播（Flink broadcast stream 消费）。
// 冻结约束：不得携带 user_ids，用户订阅由业务库和 Redis 索引维护。
type RuleMsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RuleId        int64                  `protobuf:"varint,1,opt,name=rule_id,json=ruleId,proto3" json:"rule_id,omitempty"`
	Version       int64                  `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"` // 单调递增，幂等去重
	Op            string                 `protobuf:"bytes,3,opt,name=op,proto3" json:"op,omitempty"`            // UPSERT / DELETE
	Market        Market                 `protobuf:"varint,4,opt,name=market,proto3,enum=hq.v1.Market" json:"market,omitempty"`
	Symbol        string                 `protobuf:"bytes,5,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Type          RuleType               `protobuf:"varint,6,opt,name=type,proto3,enum=hq.v1.RuleType" json:"type,omitempty"`
	Condition     string                 `protobuf:"bytes,7,opt,name=condition,proto3" json:"condition,omitempty"`                         // JSON: {"threshold":12.5} 或 {"indicator":"RSI","op":">","value":80}
	CooldownSec   int32                  `protobuf:"varint,8,opt,name=cooldown_sec,json=cooldownSec,proto3" json:"cooldown_sec,omitempty"` // 防抖冷却
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RuleMsg) Reset() {
	*x = RuleMsg{}
	mi := &file_hq_v1_push_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RuleMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuleMsg) ProtoMessage() {}

func (x *RuleMsg) ProtoReflect() protoreflect.Message {
	mi := &file_hq_v1_push_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuleMsg.ProtoReflect.Descriptor instead.
func (*RuleMsg) Descriptor() ([]byte, []int) {
	return file_hq_v1_push_proto_rawDescGZIP(), []int{0}
}

func (x *RuleMsg) GetRuleId() int64 {
	if x != nil {
		return x.RuleId
	}
	return 0
}

func (x *RuleMsg) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *RuleMsg) GetOp() string {
	if x != nil {
		return x.Op
	}
	return ""
}

func (x *RuleMsg) GetMarket() Market {
	if x != nil {
		return x.Market
	}
	return Market_A_SHARE
}

func (x *RuleMsg) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *RuleMsg) GetType() RuleType {
	if x != nil {
		return x.Type
	}
	return RuleType_PRICE_ABOVE
}

func (x *RuleMsg) GetCondition() string {
	if x != nil {
		return x.Condition
	}
	return ""
}

func (x *RuleMsg) GetCooldownSec() int32 {
	if x != nil {
		return x.CooldownSec
	}
	return 0
}

// 告警事件（notify 消费）。event_id = rule_id + rule_version + trigger_window
type AlertEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	RuleId        int64                  `protobuf:"varint,2,opt,name=rule_id,json=ruleId,proto3" json:"rule_id,omitempty"`
	Version       int64                  `protobuf:"varint,3,opt,name=version,proto3" json:"version,omitempty"`
	Market        Market                 `protobuf:"varint,4,opt,name=market,proto3,enum=hq.v1.Market" json:"market,omitempty"`
	Symbol        string                 `protobuf:"bytes,5,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Title         string                 `protobuf:"bytes,6,opt,name=title,proto3" json:"title,omitempty"`
	DetailJson    string                 `protobuf:"bytes,7,opt,name=detail_json,json=detailJson,proto3" json:"detail_json,omitempty"` // 触发时快照：价格/指标值/时间
	TriggerTs     int64                  `protobuf:"varint,8,opt,name=trigger_ts,json=triggerTs,proto3" json:"trigger_ts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AlertEvent) Reset() {
	*x = AlertEvent{}
	mi := &file_hq_v1_push_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AlertEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlertEvent) ProtoMessage() {}

func (x *AlertEvent) ProtoReflect() protoreflect.Message {
	mi := &file_hq_v1_push_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlertEvent.ProtoReflect.Descriptor instead.
func (*AlertEvent) Descriptor() ([]byte, []int) {
	return file_hq_v1_push_proto_rawDescGZIP(), []int{1}
}

func (x *AlertEvent) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *AlertEvent) GetRuleId() int64 {
	if x != nil {
		return x.RuleId
	}
	return 0
}

func (x *AlertEvent) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *AlertEvent) GetMarket() Market {
	if x != nil {
		return x.Market
	}
	return Market_A_SHARE
}

func (x *AlertEvent) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *AlertEvent) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *AlertEvent) GetDetailJson() string {
	if x != nil {
		return x.DetailJson
	}
	return ""
}

func (x *AlertEvent) GetTriggerTs() int64 {
	if x != nil {
		return x.TriggerTs
	}
	return 0
}

// 一次事件面向一个用户的投递。delivery_id = event_id + user_id
type AlertDelivery struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeliveryId    string                 `protobuf:"bytes,1,opt,name=delivery_id,json=deliveryId,proto3" json:"delivery_id,omitempty"`
	EventId       string                 `protobuf:"bytes,2,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	UserId        int64                  `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Market        Market                 `protobuf:"varint,4,opt,name=market,proto3,enum=hq.v1.Market" json:"market,omitempty"`
	Symbol        string                 `protobuf:"bytes,5,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Title         string                 `protobuf:"bytes,6,opt,name=title,proto3" json:"title,omitempty"`
	DetailJson    string                 `protobuf:"bytes,7,opt,name=detail_json,json=detailJson,proto3" json:"detail_json,omitempty"`
	TriggerTs     int64                  `protobuf:"varint,8,opt,name=trigger_ts,json=triggerTs,proto3" json:"trigger_ts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AlertDelivery) Reset() {
	*x = AlertDelivery{}
	mi := &file_hq_v1_push_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AlertDelivery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlertDelivery) ProtoMessage() {}

func (x *AlertDelivery) ProtoReflect() protoreflect.Message {
	mi := &file_hq_v1_push_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlertDelivery.ProtoReflect.Descriptor instead.
func (*AlertDelivery) Descriptor() ([]byte, []int) {
	return file_hq_v1_push_proto_rawDescGZIP(), []int{2}
}

func (x *AlertDelivery) GetDeliveryId() string {
	if x != nil {
		return x.DeliveryId
	}
	return ""
}

func (x *AlertDelivery) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *AlertDelivery) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *AlertDelivery) GetMarket() Market {
	if x != nil {
		return x.Market
	}
	return Market_A_SHARE
}

func (x *AlertDelivery) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *AlertDelivery) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *AlertDelivery) GetDetailJson() string {
	if x != nil {
		return x.DetailJson
	}
	return ""
}

func (x *AlertDelivery) GetTriggerTs() int64 {
	if x != nil {
		return x.TriggerTs
	}
	return 0
}

// 固定 ws_push topic，按 gateway_slot 路由；消息同时携带 gateway_id
type WsPushMsg struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	GatewayId   string                 `protobuf:"bytes,1,opt,name=gateway_id,json=gatewayId,proto3" json:"gateway_id,omitempty"`
	GatewaySlot uint32                 `protobuf:"varint,2,opt,name=gateway_slot,json=gatewaySlot,proto3" json:"gateway_slot,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*WsPushMsg_Quotes
	//	*WsPushMsg_Alert
	//	*WsPushMsg_Kline
	Payload       isWsPushMsg_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WsPushMsg) Reset() {
	*x = WsPushMsg{}
	mi := &file_hq_v1_push_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WsPushMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WsPushMsg) ProtoMessage() {}

func (x *WsPushMsg) ProtoReflect() protoreflect.Message {
	mi := &file_hq_v1_push_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WsPushMsg.ProtoReflect.Descriptor instead.
func (*WsPushMsg) Descriptor() ([]byte, []int) {
	return file_hq_v1_push_proto_rawDescGZIP(), []int{3}
}

func (x *WsPushMsg) GetGatewayId() string {
	if x != nil {
		return x.GatewayId
	}
	return ""
}

func (x *WsPushMsg) GetGatewaySlot() uint32 {
	if x != nil {
		return x.GatewaySlot
	}
	return 0
}

func (x *WsPushMsg) GetPayload() isWsPushMsg_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *WsPushMsg) GetQuotes() *QuoteBatch {
	if x != nil {
		if x, ok := x.Payload.(*WsPushMsg_Quotes); ok {
			return x.Quotes
		}
	}
	return nil
}

func (x *WsPushMsg) GetAlert() *AlertDelivery {
	if x != nil {
		if x, ok := x.Payload.(*WsPushMsg_Alert); ok {
			return x.Alert
		}
	}
	return nil
}

func (x *WsPushMsg) GetKline() *Kline {
	if x != nil {
		if x, ok := x.Payload.(*WsPushMsg_Kline); ok {
			return x.Kline
		}
	}
	return nil
}

type isWsPushMsg_Payload interface {
	isWsPushMsg_Payload()
}

type WsPushMsg_Quotes struct {
	Quotes *QuoteBatch `protobuf:"bytes,3,opt,name=quotes,proto3,oneof"`
}

type WsPushMsg_Alert struct {
	Alert *AlertDelivery `protobuf:"bytes,4,opt,name=alert,proto3,oneof"`
}

type WsPushMsg_Kline struct {
	Kline *Kline `protobuf:"bytes,5,opt,name=kline,proto3,oneof"`
}

func (*WsPushMsg_Quotes) isWsPushMsg_Payload() {}

func (*WsPushMsg_Alert) isWsPushMsg_Payload() {}

func (*WsPushMsg_Kline) isWsPushMsg_Payload() {}

// 合并窗口内每 symbol 只保留最新
type QuoteBatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ticks         []*Tick                `protobuf:"bytes,1,rep,name=ticks,proto3" json:"ticks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuoteBatch) Reset() {
	*x = QuoteBatch{}
	mi := &file_hq_v1_push_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuoteBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuoteBatch) ProtoMessage() {}

func (x *QuoteBatch) ProtoReflect() protoreflect.Message {
	mi := &file_hq_v1_push_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuoteBatch.ProtoReflect.Descriptor instead.
func (*QuoteBatch) Descriptor() ([]byte, []int) {
	return file_hq_v1_push_proto_rawDescGZIP(), []int{4}
}

func (x *QuoteBatch) GetTicks() []*Tick {
	if x != nil {
		return x.Ticks
	}
	return nil
}

var File_hq_v1_push_proto protoreflect.FileDescriptor

const file_hq_v1_push_proto_rawDesc = "" +
	"\n" +
	"\x10hq/v1/push.proto\x12\x05hq.v1\x1a\x12hq/v1/common.proto\x1a\x12hq/v1/market.proto\"\xf1\x01\n" +
	"\aRuleMsg\x12\x17\n" +
	"\arule_id\x18\x01 \x01(\x03R\x06ruleId\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x03R\aversion\x12\x0e\n" +
	"\x02op\x18\x03 \x01(\tR\x02op\x12%\n" +
	"\x06market\x18\x04 \x01(\x0e2\r.hq.v1.MarketR\x06market\x12\x16\n" +
	"\x06symbol\x18\x05 \x01(\tR\x06symbol\x12#\n" +
	"\x04type\x18\x06 \x01(\x0e2\x0f.hq.v1.RuleTypeR\x04type\x12\x1c\n" +
	"\tcondition\x18\a \x01(\tR\tcondition\x12!\n" +
	"\fcooldown_sec\x18\b \x01(\x05R\vcooldownSec\"\xef\x01\n" +
	"\n" +
	"AlertEvent\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12\x17\n" +
	"\arule_id\x18\x02 \x01(\x03R\x06ruleId\x12\x18\n" +
	"\aversion\x18\x03 \x01(\x03R\aversion\x12%\n" +
	"\x06market\x18\x04 \x01(\x0e2\r.hq.v1.MarketR\x06market\x12\x16\n" +
	"\x06symbol\x18\x05 \x01(\tR\x06symbol\x12\x14\n" +
	"\x05title\x18\x06 \x01(\tR\x05title\x12\x1f\n" +
	"\vdetail_json\x18\a \x01(\tR\n" +
	"detailJson\x12\x1d\n" +
	"\n" +
	"trigger_ts\x18\b \x01(\x03R\ttriggerTs\"\xf9\x01\n" +
	"\rAlertDelivery\x12\x1f\n" +
	"\vdelivery_id\x18\x01 \x01(\tR\n" +
	"deliveryId\x12\x19\n" +
	"\bevent_id\x18\x02 \x01(\tR\aeventId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\x03R\x06userId\x12%\n" +
	"\x06market\x18\x04 \x01(\x0e2\r.hq.v1.MarketR\x06market\x12\x16\n" +
	"\x06symbol\x18\x05 \x01(\tR\x06symbol\x12\x14\n" +
	"\x05title\x18\x06 \x01(\tR\x05title\x12\x1f\n" +
	"\vdetail_json\x18\a \x01(\tR\n" +
	"detailJson\x12\x1d\n" +
	"\n" +
	"trigger_ts\x18\b \x01(\x03R\ttriggerTs\"\xd9\x01\n" +
	"\tWsPushMsg\x12\x1d\n" +
	"\n" +
	"gateway_id\x18\x01 \x01(\tR\tgatewayId\x12!\n" +
	"\fgateway_slot\x18\x02 \x01(\rR\vgatewaySlot\x12+\n" +
	"\x06quotes\x18\x03 \x01(\v2\x11.hq.v1.QuoteBatchH\x00R\x06quotes\x12,\n" +
	"\x05alert\x18\x04 \x01(\v2\x14.hq.v1.AlertDeliveryH\x00R\x05alert\x12$\n" +
	"\x05kline\x18\x05 \x01(\v2\f.hq.v1.KlineH\x00R\x05klineB\t\n" +
	"\apayload\"/\n" +
	"\n" +
	"QuoteBatch\x12!\n" +
	"\x05ticks\x18\x01 \x03(\v2\v.hq.v1.TickR\x05ticks*\\\n" +
	"\bRuleType\x12\x0f\n" +
	"\vPRICE_ABOVE\x10\x00\x12\x0f\n" +
	"\vPRICE_BELOW\x10\x01\x12\x0f\n" +
	"\vPRICE_RANGE\x10\x02\x12\x0e\n" +
	"\n" +
	"PCT_CHANGE\x10\x03\x12\r\n" +
	"\tINDICATOR\x10\x04B_\n" +
	"\x18com.hqpush.contract.hqv1B\tPushProtoP\x01Z6github.com/hqpush/gate/packages/contract/go/hq/v1;hqv1b\x06proto3"

var (
	file_hq_v1_push_proto_rawDescOnce sync.Once
	file_hq_v1_push_proto_rawDescData []byte
)

func file_hq_v1_push_proto_rawDescGZIP() []byte {
	file_hq_v1_push_proto_rawDescOnce.Do(func() {
		file_hq_v1_push_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_hq_v1_push_proto_rawDesc), len(file_hq_v1_push_proto_rawDesc)))
	})
	return file_hq_v1_push_proto_rawDescData
}

var file_hq_v1_push_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_hq_v1_push_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_hq_v1_push_proto_goTypes = []any{
	(RuleType)(0),         // 0: hq.v1.RuleType
	(*RuleMsg)(nil),       // 1: hq.v1.RuleMsg
	(*AlertEvent)(nil),    // 2: hq.v1.AlertEvent
	(*AlertDelivery)(nil), // 3: hq.v1.AlertDelivery
	(*WsPushMsg)(nil),     // 4: hq.v1.WsPushMsg
	(*QuoteBatch)(nil),    // 5: hq.v1.QuoteBatch
	(Market)(0),           // 6: hq.v1.Market
	(*Kline)(nil),         // 7: hq.v1.Kline
	(*Tick)(nil),          // 8: hq.v1.Tick
}
var file_hq_v1_push_proto_depIdxs = []int32{
	6, // 0: hq.v1.RuleMsg.market:type_name -> hq.v1.Market
	0, // 1: hq.v1.RuleMsg.type:type_name -> hq.v1.RuleType
	6, // 2: hq.v1.AlertEvent.market:type_name -> hq.v1.Market
	6, // 3: hq.v1.AlertDelivery.market:type_name -> hq.v1.Market
	5, // 4: hq.v1.WsPushMsg.quotes:type_name -> hq.v1.QuoteBatch
	3, // 5: hq.v1.WsPushMsg.alert:type_name -> hq.v1.AlertDelivery
	7, // 6: hq.v1.WsPushMsg.kline:type_name -> hq.v1.Kline
	8, // 7: hq.v1.QuoteBatch.ticks:type_name -> hq.v1.Tick
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_hq_v1_push_proto_init() }
func file_hq_v1_push_proto_init() {
	if File_hq_v1_push_proto != nil {
		return
	}
	file_hq_v1_common_proto_init()
	file_hq_v1_market_proto_init()
	file_hq_v1_push_proto_msgTypes[3].OneofWrappers = []any{
		(*WsPushMsg_Quotes)(nil),
		(*WsPushMsg_Alert)(nil),
		(*WsPushMsg_Kline)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_hq_v1_push_proto_rawDesc), len(file_hq_v1_push_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_hq_v1_push_proto_goTypes,
		DependencyIndexes: file_hq_v1_push_proto_depIdxs,
		EnumInfos:         file_hq_v1_push_proto_enumTypes,
		MessageInfos:      file_hq_v1_push_proto_msgTypes,
	}.Build()
	File_hq_v1_push_proto = out.File
	file_hq_v1_push_proto_goTypes = nil
	file_hq_v1_push_proto_depIdxs = nil
}
